/* eslint-disable @next/next/no-img-element */
import { RichText } from "prismic-dom";
import Head from "next/head";
import styles from "../styles/home.module.scss";
import Image from "next/image";
import Prismic from "@prismicio/client";

import techsImage from "../../public/images/techs.svg";
import { GetStaticProps } from "next";
import { getPrismicClient } from "../services/prismic";

type TContent = {
  title: string,
  titleContent: string,
  linkAction: string,
  mobileTitle: string,
  mobileContent: string,
  mobileBanner: string,
  webTitle: string,
  webContent: string,
  webBanner: string,
}

interface IProps {
  content: TContent
}

const Home = ({content}: IProps) => {
  console.log(content);
  
  return (
    <>
      <Head>
        <title>Institucional</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.container}>
        <div className={styles.containerHeader}>
          <section className={styles.ctaText}>
            <h1>{content.title}</h1>
            <span>{content.titleContent}</span>
            <a href={content.linkAction}>
              <button>START NOW!</button>
            </a>
          </section>
          <img src='/images/banner-conteudos.png' alt='Banner Content' />
        </div>

        <hr className={styles.divisor} />

        <div className={styles.sectionContent}>
          <section>
            <h2>{content.mobileTitle}</h2>
            <span>
            {content.mobileContent}
            </span>
          </section>
          <img src={content.mobileBanner} alt='Mobile Content Develop' />
        </div>
        <hr className={styles.divisor} />

        <div className={styles.sectionContent}>
          <img src={content.webBanner} alt='Web development' />
          <section>
            <h2>{content.webTitle}</h2>
            <span>
            {content.webContent}
            </span>
          </section>
        </div>

        <div className={styles.nextLevelContent}>
          <Image src={techsImage} alt='techs' />
          <h2>
            More than <span className={styles.students}>15k</span> already took
            their career to the next level
          </h2>
          <span>
            And you going to miss your opportunity to be your best version?
          </span>
          <a href=''>
            <button>ACCESS COURSE</button>
          </a>
        </div>
      </main>
    </>
  );
}

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const prismic = getPrismicClient();

  const response = await prismic.query([
    Prismic.Predicates.at("document.type", "home"),
  ]);
  const {
    title,
    sub_title,
    link_action,
    mobile,
    mobile_content,
    mobile_banner,
    title_web,
    web_content,
    web_banner,
  } = response.results[0].data;
  
  const content = {
    title: RichText.asText(title),
    titleContent: RichText.asText(sub_title),
    linkAction: link_action.url,
    mobileTitle: RichText.asText(mobile),
    mobileContent: RichText.asText(mobile_content),
    mobileBanner: mobile_banner.url,
    webTitle: RichText.asText(title_web),
    webContent: RichText.asText(web_content),
    webBanner: web_banner.url,
  };
  return {
    props: { content },
    revalidate: 60 * 60,
  };
};
